### ISSUE TITLE
Doesn't seem to do anything. Followed instructions but can't figure out how to trigger the dropbox upload.

### ISSUE THREAD

**Issue by drewmmiranda** [danielwelch/hassio-dropbox-sync#54]
Doesn't seem to do anything. Followed instructions but can't figure out how to trigger the dropbox upload.

No info in the addon log. Unsure how to make use of this.

**Comment by sbingg** [comment]
You need to trigger an automation and call the service:
see here:
```
action:
  - service: hassio.addon_stdin
    data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload

```
Due to the fact the Dropbox is no longer providing long-live app tokens, you will need to update the token manually or see here https://github.com/danielwelch/hassio-dropbox-sync/issues/50#issuecomment-1220221301
